### ISSUE TITLE
RL Turnier 

### ISSUE THREAD

**Issue by GraV1337y** [PG642/Wiki#3]
Turnier planen und Umfrage auswerten!

**Comment by Kabumba** [comment]
[RL Turnier teams.txt](https://github.com/PG642/OrgaRepo/files/6479700/RL.Turnier.teams.txt)

**Comment by Kabumba** [comment]
Teams
     1          2          3          4
 01 07 06 | 02 05 08 | 03 09 10 | 04 11 12 | 1. Turnier
 01 08 11 | 02 07 12 | 03 06 05 | 04 09 10 | 2. Turnier
 01 05 10 | 02 09 11 | 03 07 12 | 04 06 08 | 3. Turnier
 01 09 12 | 02 06 10 | 03 08 11 | 04 07 05 | 4. Turnier

Spieler 09 und 10, 08 und 11, 07 und 12 spielen jeweils 2 mal miteinander
Spieler 01, 02, 03 und 04 spielen nie miteinander

**Comment by Kabumba** [comment]
Turnierstruktur: Halbfinale -> Finale ODER jeder gegen jeden (2 spiele pro team vs 3 spiele pro team)?

**Comment by Kabumba** [comment]
Spielernummern:

01 Jannik
02 Yannik W.
03 Thilo
04 Sebastian
05 Matthias
06 Konstantin
07 Alex
08 Oliver
09 Hendrik M.
10 Leon
11 Frederik
12 Marco

**Comment by GraV1337y** [comment]
Das passt dann aber mit der Spielerstärke nicht wenn du meinst dass 10-12 die stärksten und und 7-9 die Schwächsten sein sollen

**Comment by Kabumba** [comment]
Ich habe mir da neue gedanken drüber gemacht
das mit 10-12 am stärksten und 7-9 am schwächsten war eher darauf bezogen dass diese zweiergruppen ähnlich stark sein sollen
können also auch 2 mittelgute spieler sein
wichtiger fand ich dann eher, dass in jedem team jemand starkes ist und dass die stärksten spieler möglichst nicht zusammen in einem team sind. Hab da n graph erstellt wer nie mit wem spielt und so und das dann so ausgeklügelt

**Comment by Kabumba** [comment]
Wichtiger ist die frage nach dem turnierformat

**Comment by GraV1337y** [comment]
Ich denke können beide Formen mal ansprechen und je nachdem wie dann das Interesse da ist. Ist ja primär eine Zeit und Lust Frage
