### ISSUE TITLE
Wiki Aufbau 

### ISSUE THREAD

**Issue by TheImus** [PG642/Wiki#5]
Wie soll das Wiki strukturiert werden und ist es nutzbar für den Projektbericht

**Comment by TheImus** [comment]
Man kann das Side Menü mit ein bisschen mehr Aufwand als Menü nutzen. Man muss nur händisch das Menü pflegen. Ansonsten geht das eigentlich ganz gut.

**Comment by GraV1337y** [comment]
Habe mich da auch nochmal erkundigt, ob es möglich ist eine Art "Dropdown-Menu" oder ähnliches einzufügen, jedoch bisher ohne Erfolgt. Scheint so als wäre das die einzige Möglichkeit die es gibt um es ein bisschen übersichtlicher zu machen.
